<?php echo $this->render('header.phtml'); ?>
<?php echo $this->render('menu.phtml'); ?>

<div id="contenido">
<h2><?php echo $this->indextitle; ?></h2>

<?php if ($this->usuarioLogueado): ?>
    <div class="menu-admin">
    	<a href="<?php echo $this->baseUrl; ?>/usuarios/usuarios/agregar"><?php echo $this->adduser; ?></a><br><br>
    </div>    
<?php endif; ?>

    <table border="1">
    <tr>
         <th><?php echo $this->username; ?></th>
         <th><?php echo $this->name; ?></th>
         <th><?php echo $this->lastname; ?></th>
    <?php if ($this->usuarioLogueado): ?>
        <th><?php echo $this->email; ?></th>
         <th colspan="3"><?php echo $this->actions; ?></th>
    <?php endif; ?>

    </tr>
    <?php
    foreach( $this->usuarios as $usuario ) : ?>
            <tr>
                <td><?php echo $this->escape($usuario->usuario);?></td>


                <td><?php echo $this->escape($usuario->nombre);?></td>
                <td><?php echo $this->escape($usuario->apellido);?></td>
                
            <?php if ($this->usuarioLogueado): ?>
                <td><?php echo $this->escape($usuario->mail);?></td>
                <td nowrap="nowrap">
                	<div class="menu-admin">
	                	<a href="<?php echo $this->baseUrl; ?>/usuarios/usuarios/ver/id/<?php echo $usuario->id;?>"><?php echo $this->view; ?></a>
    	            	<a href="<?php echo $this->baseUrl; ?>/usuarios/usuarios/modificar/id/<?php echo $usuario->id;?>"><?php echo $this->modify; ?></a>
        	        	<a href="<?php echo $this->baseUrl; ?>/usuarios/usuarios/eliminar/id/<?php echo $usuario->id;?>"><?php echo $this->delete; ?></a>
        	        </div>
        	    </td>
            <?php endif; ?>

            </tr>
    <?php endforeach; ?>
    </table>

<?php if ($this->usuarioLogueado): ?>
    <div class="menu-admin">
    	<br><a href="<?php echo $this->baseUrl; ?>/usuarios/usuarios/agregar"><?php echo $this->adduser; ?></a><br><br>
    </div>    
<?php endif; ?>

</div>

<?php echo $this->render('footer.phtml'); ?>