<?php echo $this->render('header.phtml'); ?>
<?php echo $this->render('menu.phtml'); ?>

<div id="noticia">
	
	<h1>Agregar Nueva Noticia</h1>
	
	<form action="<?php echo $this->baseUrl ?>/noticias/admin/agregar" method="post">
	    <div>
	      <label for="titulo">titulo</label><br>
	      <input type="text" name="titulo" size="90" value="<?php echo $this->escape(trim($this->noticias->titulo));?>"/>
	    </div>
	    <br>

	    <div>
	    	<label for="titulo">contenido</label><br>
	    	<textarea rows="10" cols="80" name="contenido"><?php echo $this->escape(trim($this->noticias->contenido));?></textarea>
	    </div>
	   	<br>
   
	    <div>
	    	<label for="titulo">contenido ext</label><br>
	    	<textarea rows="10" cols="80" name="contenido_ext"><?php echo $this->escape(trim($this->noticias->contenido_ext));?></textarea>
	    </div>
	   	<br>

	    <div id="boton_formulario">
	      <input type="hidden" name="id" value="<?php echo $this->noticias->id; ?>" />
	      <input type="submit" name="add" value="Agregar" />
	    </div>
	
	</form>
</div>	

<?php echo $this->render('footer.phtml'); ?>

