<?php echo $this->render('header.phtml'); ?>
<?php echo $this->render('menu.phtml'); ?>

<div id="contenido">
<h2><?php echo $this->deleteusertitle; ?></h2>

<?php if ($this->usuario) :?>
  <form action="<?php echo $this->baseUrl ?>/usuarios/admin/eliminar" method="post">
    <p><?php echo $this->acceptdelete; ?> <?php echo $this->escape($this->usuario->usuario); ?>'?</p>
    <div id="boton_formulario">
      <input type="hidden" name="id" value="<?php echo $this->usuario->id; ?>" />
      <input type="submit" name="del" value="<?php echo $this->yes; ?>" />
      <input type="submit" name="del" value="<?php echo $this->no; ?>" />
    </div>
  </form>
<?php else: ?>
  <p><?php echo $this->notfounduser; ?></p>
<?php endif;?>
</div>


<?php echo $this->render('footer.phtml'); ?>