<?php

/**
 * Default home page view
 *  
 * @author
 * @version
 */

echo '<?xml version="1.0" encoding="UTF-8" ?>';
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<title>New Zend Framework Project</title>
</head>

<body>
	<h3>Tus Contactos de Gmail</h3>
    <div>
        <form action="apigmail/viewlink/" method="post" name="contactosGmail"> 
        <fieldset>
                <legend>Usuario de gmail</legend>
                <input type="text" size="20" name="user" id="user" />@gmail.com
                <br />
                <input type="submit" value="Enviar" />
        </fieldset>
        </form>
    </div>  
</body>

</html>
