<?php echo $this->render('header.phtml'); ?>
<?php echo $this->render('menu.phtml'); ?>
	<h1>
		Agregar Nueva Noticia
	</h1>
	<form action="<?php echo $this->baseUrl ?>/noticias/admin/agregar" method="post">
		<table>
			<tr>
				<th>T&iacute;tulo</th>
				<td><input type="text" id="titulo" name="titulo" /></td>
			</tr>
			<tr>
				<th>Fecha</th>
				<td><input type="text" id="fecha" name="fecha" /></td>
			</tr>
			<tr>
				<td colspan="2" align="center"><input type="submit" id="boton" value="Grabar" /></td>
			</tr>
		</table>
	</form>
<?php echo $this->render('footer.phtml'); ?>