<?php echo $this->render('header.phtml'); ?>
<?php echo $this->render('menu.phtml'); ?>

<div id="contenido">
<h2>Eliminar</h2>

<?php if ($this->noticias) :?>

  <form action="<?php echo $this->baseUrl ?>/noticias/admin/eliminar" method="post">
    <p>¿Esta seguro que quiere eliminar la noticia
    '<?php echo "'{$this->escape(trim($this->noticias->titulo))}'"; ?>'?
    </p>
    <div id="boton_formulario">
      <input type="hidden" name="id" value="<?php echo $this->noticias->id; ?>" />
      <input type="submit" name="del" value="Si" />
      <input type="submit" name="del" value="No" />
    </div>
  </form>

<?php else: ?>
  <p>No se pudo encontrar la noticia.</p>
<?php endif;?>
</div>


<?php echo $this->render('footer.phtml'); ?>