<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>New Zend Framework Project</title>
</head>

<body>
    Hello, world!<br>

    Bienvenido a la página por defecto.


  <ul>
    <li><a href="noticias/">Modulo Noticias</a><br/>
    </li>

  </ul>

</body>

</html>
